name = "catedge"
compatibility_date = "2025-08-04"
main = "server.js"
node_compat = true

[build]
command = "npm run build && npm run cf-pages"

[pages]
pages_build_output_dir = ".vercel/output/static"